-- App-specific tweaks
require("default/hypr/apps/browser")
require("default/hypr/apps/hyprshot")
require("default/hypr/apps/jetbrains")
require("default/hypr/apps/localsend")
require("default/hypr/apps/pip")
require("default/hypr/apps/qemu")
require("default/hypr/apps/retroarch")
require("default/hypr/apps/steam")
require("default/hypr/apps/geforce")
require("default/hypr/apps/moonlight")
require("default/hypr/apps/system")
require("default/hypr/apps/terminals")
require("default/hypr/apps/walker")
require("default/hypr/apps/webcam-overlay")
