# If not running interactively, don't do anything (leave this at the top of this file)
[[ $- != *i* ]] && return

# All the default Omarchy aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/omarchy/default/bash/rc

# Personal alias and functions start here
# Aliases are here

# nvim config
nvimc() {
    pushd ~/.config/nvim || return 1
    nvim .
    popd
}

# fff file manager
f() {
    local prev_dir="$PWD"
    local cache_dir="${XDG_CACHE_HOME:-$HOME/.cache}/fff"
    fff "$@"
    local new_dir
    new_dir="$(cat "$cache_dir/.fff_d")"
    if [[ "$new_dir" != "$prev_dir" ]]; then
        cd "$new_dir"
        # Save current history to file
        history -a
        history -s "cd $PWD"
        # Append 'cd <path>' command to history file
        shopt -s histappend
        history -w "$HISTFILE"
    fi
}
