# If not running interactively, don't do anything (leave this at the top of this file)
[[ $- != *i* ]] && return

# All the default Omarchy aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/omarchy/default/bash/rc

# Personal alias and functions start here
# Aliases are here

# nvim config
nvimc() {
    pushd ~/.config/nvim || return 1
    nvim .
    popd
}
