source = ~/.config/omarchy/current/theme/hyprlock.conf

general {
    ignore_empty_input = true
}

background {
    monitor =
    color = $color
    path = screenshot
    blur_passes = 3
    blur_size = 8
}

animations {
    enabled = true
}

# Time and Date
# Block 1: Hours (Large, Left side)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H')"
    color = $font_color
    font_size = 115
    font_family = GeistMono Nerd Font ExtraBold
    position = -50, 140   # Negative X moves it left of center
    halign = center
    valign = center
}

# Block 2: Minutes (Top right)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%M')"
    color = $font_color
    font_size = 65
    font_family = GeistMono Nerd Font ExtraBold
    position = 100, 160     # Positive Y moves it up
    halign = center
    valign = center
}

# Block 3: Date (Bottom right)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%d/%m')"
    color = $font_color
    font_size = 25
    font_family = GeistMono Nerd Font
    position = 100, 100     # Lower Y, slightly offset X to align with minutes
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 500, 80
    position = 0, 0
    halign = center
    valign = center

    inner_color = rgba(0, 0, 0, 0.0)
    outer_color = $outer_color
    outline_thickness = 2

    font_family = GeistMono Nerd Font
    font_color = $font_color

    placeholder_text = passwd
    check_color = $check_color
    fail_text = <i>$FAIL ($ATTEMPTS)</i>

    rounding = 4
    shadow_passes = 0
    fade_on_empty = false
}

auth {
    fingerprint:enabled = false
}
