format = """
[](fg:#363646)\
$directory\
[](fg:#363646 bg:#2A2A37)\
$git_branch\
$git_status\
[](fg:#2A2A37 bg:#1F1F28)\
$nodejs\
$rust\
$golang\
$php\
$python\
[](fg:#1F1F28)\
$cmd_duration\
\n$character"""

[cmd_duration]
min_time = 0
style = "fg:#C8C093"
format = '[[ $duration](fg:#C8C093)]($style)'
show_milliseconds = false

[directory]
style = "bg:#363646 fg:#DCD7BA"
format = "[$path]($style)"
truncation_length = 0
truncate_to_repo = false

[git_branch]
symbol = ""
style = "bg:#2A2A37"
format = '[[ $symbol $branch ](fg:#938AA9 bg:#2A2A37)]($style)'

[git_status]
format     = '[[$all_status](fg:#938AA9 bg:#2A2A37)]($style)'
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

[nodejs]
symbol = ""
style = "bg:#1F1F28"
format = '[[ $symbol ($version) ](fg:#957FB8 bg:#1F1F28)]($style)'

[rust]
symbol = ""
style = "bg:#1F1F28"
format = '[[ $symbol ($version) ](fg:#957FB8 bg:#1F1F28)]($style)'

[golang]
symbol = ""
style = "bg:#1F1F28"
format = '[[ $symbol ($version) ](fg:#957FB8 bg:#1F1F28)]($style)'

[php]
symbol = ""
style = "bg:#1F1F28"
format = '[[ $symbol ($version) ](fg:#957FB8 bg:#1F1F28)]($style)'

# Only show Python if inside virtualenv
[python]
symbol = ""
style = "bg:#1F1F28"
format = "[ $symbol $virtualenv ($version) ](fg:#957FB8 bg:#1F1F28)($style)"
pyenv_version_name = false
detect_extensions = []
detect_files = []
python_binary = ["python", "python3", "python2"]

# Customize ❯ symbol
[character]
success_symbol = "[ ↳](fg:#DCD7BA)"
error_symbol = "[ ↳](fg:#FF5D62)"
